name: 'Jest Coverage Action'
description: 'Run jest coverage'
runs:
  using: 'node12'
  main: 'dist/index.js'
inputs:
  jest-bin:
    required: true
    description: 'Path to your jest library, probably node_modules/.bin/jest'
branding:
  icon: check-circle
  color: red
