name: 'Jest Coverage Action'
description: 'Run jest coverage'
runs:
  using: 'node12'
  main: 'dist/index.js'
inputs:
  jest-bin:
    required: true
    description: 'Path to your jest library, probably ./node_modules/.bin/jest'
  custom-working-directory:
    required: false
    description: 'Path to your working directory, uses `.` if not provided'
  coverage-data-path:
    required: true
    description: 'Path to your coverage file, probably ./coverage/coverage-final.json'
  check-run-subtitle:
    required: false
    description: 'A subtitle to add to the check run when annotations are passed back to avoid overwriting each other'
branding:
  icon: check-circle
  color: red
