name: 'Jest Coverage Action'
description: 'Run jest coverage'
runs:
  using: 'node12'
  main: 'dist/index.js'
inputs:
  jest-bin:
    required: true
    description: 'Path to your jest library, probably ./node_modules/.bin/jest'
  coverage-data-path:
    required: true
    description: 'Path to your coverage file, probably ./coverage/coverage-final.json'
branding:
  icon: check-circle
  color: red
